# Generated by Django 5.2.4 on 2025-07-11 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=10)),
                ('ie', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_cliente', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('rg', models.CharField(max_length=20)),
                ('cnh_numero', models.CharField(max_length=20)),
                ('cnh_categoria', models.CharField(max_length=5)),
                ('validade_cnh', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField()),
                ('prazo_entrega_previsto', models.DateField()),
                ('data_entrega_real', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(max_length=30)),
                ('prioridade', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_por', models.CharField(max_length=50)),
                ('data_criacao', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cte_numero', models.CharField(max_length=20)),
                ('cte_chave_acesso', models.CharField(max_length=44)),
                ('cte_data_emissao', models.DateField()),
                ('cte_status_sefaz', models.CharField(max_length=20)),
                ('cte_xml', models.TextField()),
                ('data_saida', models.DateField()),
                ('data_prevista_entrega', models.DateField()),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('criado_por', models.CharField(max_length=50)),
                ('data_criacao', models.DateField()),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.motorista')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
        ),
    ]
